[package]
name = "stronghold"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = "Apache-2.0"
repository = "https://github.com/iotaledger/stronghold.rs"
default-run = "stronghold"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.11", features = [ "all-api" ] }
futures = "0.3"
riker = "0.4"
bincode = "1.3.1"

  [dependencies.tauri-plugin-authenticator]
  git = "https://github.com/tauri-apps/tauri-plugin-authenticator"
  rev = "dbddf7c417e8cd10bae9928977f5f093430d51da"

  [dependencies.tauri-plugin-stronghold]
  git = "https://github.com/tauri-apps/tauri-plugin-stronghold"
  rev = "6749525a47a95439c9703d3a49b94ac65660998f"

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "stronghold"
path = "src/main.rs"
