[package]
name = "stronghold"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = "Apache-2.0"
repository = "https://github.com/iotaledger/stronghold.rs"
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version="1.0.0-beta.4", features = ["api-all", "menu", "system-tray"] }
# tauri = { git = "https://github.com/tauri-apps/tauri", rev = "49fb3b72255993ea6f92e8d475021adac0c914a7", features = ["api-all", "system-tray", "menu"] }
thiserror = "1.0.25"
futures = "0.3"
riker = "0.4"
bincode = "1.3.1"

[dependencies.tauri-plugin-authenticator]
branch = "dev"
git = "https://github.com/tauri-apps/tauri-plugin-authenticator"
# path = "../../../../tauri-plugin-authenticator"

[dependencies.tauri-plugin-stronghold]
branch = "main"
git = "https://github.com/tauri-apps/tauri-plugin-stronghold"
# path = "../../../../tauri-plugin-stronghold"

# [patch.crates-io]
# tao = { git = "https://github.com/tauri-apps/tao", rev = "5be88eb9488e3ad27194b5eff2ea31a473128f9c" }

[build-dependencies]
tauri-build = "1.0.0-beta.2"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

# for final bundle minification
# [profile.release]
# panic = "abort"
# codegen-units = 1
# lto = true
# incremental = false
# opt-level = "z"
